## Basic Tensor Operations

In [ ]:
#Listing 2.1 – Creating a 2 dimensional vector
import torch
print(torch.__version__)
print(torch.cuda.is_available())

In [ ]:

import numpy
# numpy.version.version

a =torch.tensor([[[[1,2,2,3],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]],[[[1,2,2,3],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]]])
print(a)
a.size()
#Listing 2.2 – Shape of a tensor
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]])
a.shape
a
#Listing 2.3 – Shape of a tensor (continued)
b = torch.tensor([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6]])
b
b.shape
#Listing 2.4 – Creating tensors with arbitary dimensions
c = torch.tensor([[[0.1],[0.2]],[[0.3],[0.4]]])
c.shape
import torch
print(torch.cuda.is_available())

#Listing 2.5 – Tensors with Numpy
a = torch.tensor(numpy.array(([[[[1.,2.,2.,3.],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]],[[[1,2,2,3],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]]])))

a = numpy.array(([[[[1.,2.,2.,3.],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]],[[[1,2,2,3],[1,1,1,1],[2,2,2,2]],[[1,2,2,3],[1,1,1,1],[2,2,2,2]]]]))
c = torch.tensor(a)
c
a.shape
#Listing 2.6 - Tensors from Numpy
import numpy as np
a = np.array([1, 2, 3, 4, 5])
tensor_a = torch.from_numpy(a)
tensor_a
#Listing 2.7 – Defining tensor datatypes
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float32)
a
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float64)
        
a
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float16)
                
a

import torch
# Create random matrices A and B
A = torch.rand(10000, 5000).cuda()  # Move to GPU
B = torch.rand(5000, 10000).cuda()

# Perform matrix multiplication
C = torch.matmul(A, B)  # Or C = A @ B

# Print the result (C)
print(C)
#Listing 2.8 – Constructing tensors with random values
r = torch.rand(2,2,2)

r
r.shape
#Listing 2.9 – Tensors with zeros
zeros = torch.zeros(2,2,3)

zeros
zeros.shape
#Listing 2.10 – Tensors of ones
ones = torch.ones(2,2,3)

ones

ones.shape
#Listing 2.11 – Identity maxtix tensors
i = torch.eye(3)

i

i.shape

In [ ]:
#Listing 2.12 – Tensors filled with an arbitary value
f = torch.full((3,3), 0.42)

f

In [ ]:
f.shape

In [ ]:
#Listing 2.13 – Tensors with linearly spaced floating-point numbers
lin = torch.linspace(0, 20, steps=5)

lin

In [ ]:
#Listing 2.14- Tensors with logarithmically spaced floating-point numbers
log = torch.logspace(-3, 3, steps=4)

log

In [ ]:
#Listing 2.15 – Creating a tensor with dimensions similar to another tensor
a = torch.tensor([[0.5, 0.5],[0.5, 0.5]])

b = torch.zeros_like(a)

b

In [ ]:
c = torch.ones_like(a)
        
c

In [ ]:
#Listing 2.16 – Tensor with int dtype
i = torch.tensor([[1,2],[3,4]])

i

In [ ]:
i.dtype

In [ ]:
i = torch.tensor([[1,2],[3,4]], dtype=torch.int)
        
i


In [ ]:
#Listing 2.17 – Tensors as a range of integers
a = torch.arange(1,10, step=2)

a

In [ ]:
#Listing 2.18 – Tensors with random permutation of integers
r = torch.randperm(10)
r

### Tensor Munging Operations

In [ ]:
#Listing 2.19 – Accessing individual members of a tensor
a = torch.tensor([[1,2],[3,4]])
a

In [ ]:
print(a[0][0])       
print(a[0][1])
print(a[1][0])
print(a[1][1])
print(a.shape)

In [ ]:
#Listing 2.20 – Accessing values from a tensor with a single value
a = torch.tensor([[[[0.42]]]])
print(a)
print(a.type)
print(a.shape)
print(a.item())

In [ ]:
#Listing 2.21 – Reshaping a tensor
a = torch.zeros(10)
print(a)
print(a.shape)

b = a.view(2,5)
print(b)
print(b.shape)

In [ ]:
#Listing 2.22 – Verifying the size of a tensor after reshaping
a = torch.arange(1,10)
print(a)
print(a.shape)

b = a.view(3,3)
print(b)
print(b.shape)

In [ ]:
#Listing 2.23 – Concatenating two tensors
a = torch.zeros(2,2)
print(a)
print(a.shape)

b = torch.cat([a,a,a],0)
print(b)
print(b.shape)
                                                
c = torch.cat([a,a,a],1)                                     
print(c)
print(c.shape)

In [ ]:
#Listing 2.24 – Stacking tensors together

a = torch.tensor([1,2,3,4])
a =a.view(2,2)
print(a)
print(a.shape)

b = torch.stack([a,a,a], 0)
print(b)
print(b.shape)
                                           
c = torch.stack([a,a,a], 1)                                       
print(c)
print(c.shape)

d = torch.stack([a,a,a], 2)
print(d)
print(d.shape)

In [ ]:
#Listing 2.25 – Chunking/chopping tensors 
a = torch.zeros(10, 1)
print(a)
print(a.shape)
                                                                     
b = torch.chunk(a, 5, 0)                                                                       
print(b)

In [ ]:
#Listing 2.26 – Chunking/chopping tensors continued
d = torch.chunk(a, 3, 0)
print(d)

In [ ]:
#Listing 2.27 – Splitting tensors
import numpy as np
a = np.zeros(10)
for i in range(10):
    a[i] = i

print(a)
a = torch.from_numpy(a)
print(a)
print(a.shape)
                                                           
b = torch.split(a,2,0)
                                                                        
print(b)


In [ ]:
#Listing 2.28 – Extracting parts of tensors using index_select
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])

print(a)
print(a.shape)
                
index = torch.LongTensor([0, 1])
                
b = torch.index_select(a, 0, index)
                
print(b)
print(b.shape)
                        
c = torch.index_select(a, 1, index)
                        
print(c)                              
print(c.shape)



In [ ]:
#Listing 2.29 – Selecting elements from a tensor using masked_select
a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
                
mask = torch.BoolTensor([[0, 1, 0],[1, 1, 1],[0, 1, 0]])
                
print(mask)
print(mask.shape)
                               
b = torch.masked_select(a, mask)                              
print(b)                        
print(b.shape)

In [ ]:
#Listing 2.30 – Reshaping tensor with squeeze
a = torch.zeros(2,2,1)

print(a)

print(a.shape)
                          
b = a.squeeze()
                          
print(b)
                                  
print(b.shape)



In [ ]:
#Listing 2.31 – Reshaping tensor with unsqueeze

a = torch.zeros(2,2)

print(a)
print(a.shape)
        
b = torch.unsqueeze(a, 0)
        
print(b)
                 
print(b.shape)
                 
c = torch.unsqueeze(a, 1)
                 
print(c)
                         
print(c.shape)
                         
d = torch.unsqueeze(a, 2)
                         
print(d)
                                                   
print(d.shape)




In [ ]:
#Listing 2.32 – Extracting parts of a tensor using unbind
a
print(a.shape)               
print(torch.unbind(a, 0))                
print(torch.unbind(a, 1))

In [ ]:
#Listing 2.33 – Constructing tensor from existing tensor using where clause
a = torch.zeros(3,3)
print(a)
print(a.shape)
                
b = torch.ones(3,3)               
print(b)
print(b.shape)                               
c = torch.rand(3,3)                              
print(c)                                              
print(c.shape)                                             
d = torch.where(c > 0.5, a, b)                                              
print(d)
print(d.shape)

In [ ]:
#Listing 2.34 – Logical operations on tensors using any and all
a = torch.rand(3,3)

print(a)
print(a.shape)

print(torch.any(a > 0))
print(torch.any(a > 1.0))
print(torch.all(a > 0))
print(torch.all(a > 1.0))

In [ ]:
#Listing 2.35 – Reshaping tensors
a = torch.arange(1,10)
print(a)

b = a.view(3,3)
print(b)
print(b.shape)
                
c = a.view(3,-1)
                
print(c)
print(c.shape)

In [ ]:
#Listing 2.36 – Collapsing the dimensions of a tensor using flatten
a = torch.ones([2,2,2,2])
print(a)
print(a.shape)

b = torch.flatten(a)
print(b)
print(b.shape)

c = torch.flatten(a, start_dim=0)
print(c)
print(c.shape)

d = torch.flatten(a, start_dim=1)
print(d)
print(d.shape)

e = torch.flatten(a, start_dim=2)
print(e)
print(e.shape)

f = torch.flatten(a, start_dim=3)
print(f)
print(f.shape)

In [ ]:
#Listing 2.37 – Extract values from tensor using gather
a = torch.rand(4,4)

print(a)
print(a.shape)                       
b = torch.LongTensor([[0,1,2,3]])
                        
print(b)
print(b.shape)

c = a.gather(0,b)
print(c)
                        
print(c.shape)
                        
d = torch.LongTensor([[0],[1],[2],[3]])
                        
print(d)
print(d.shape)

                                                
e = a.gather(1,d)
                                                
print(e)
print(e.shape)

In [ ]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)
print(t.shape)

v = torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))
print(v)
print(v.shape)

In [ ]:
#Listing 2.38 – Augmenting tensors values with scatter
a = torch.rand(4,4)
print(a)
print(a.shape)
 
index = torch.LongTensor([[0,1,2,3]])               
print(index)                      
print(index.shape)
                        
values = torch.zeros(1,4)                       
print(values)                       
print(values.shape)
                        
result = a.scatter(0, index, values)                      
print(result)
print(result.shape)
print(a)

In [ ]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)
print(t[0][0])
print(t[1][0])
print(t[0][1])
print(t[1][1])
v =torch.scatter(t, 1, torch.tensor([[0, 0], [1, 0]]), torch.tensor([[10, 20], [30, 40]]))
print(v)

In [ ]:
import torch

t = torch.tensor([[1, 2], [3, 4]])
print("Original tensor t:")
print(t)

# Create a 2D index tensor
index = torch.tensor([[0, 0], [0, 1]])
values = torch.tensor([[10, 20],[30, 40]])

# Scatter values along dimension 0
v = torch.scatter(t, 0, index, values)
print("Scattered tensor v:")
print(v)

In [ ]:
import numpy as np
src = torch.from_numpy(np.arange(1, 11)).float().view(2, 5)
print(src)
input_tensor = torch.zeros(3, 5)
print(input_tensor)
index_tensor = torch.tensor([[0, 1, 2], [1, 3, 4]])
print(index_tensor)
dim = 1
input_tensor.scatter_(dim, index_tensor, src)
print("Scattered tensor:")
print(input_tensor)

## Mathematical Operations

In [ ]:
#Listing 2.39 – Validating if given tensors are within a tolerance level
a = torch.rand(3,3)
print(a)
b = a + a * 1e-3             
print(b)
print(torch.allclose(a,b,rtol=1e-1))                               
print(torch.allclose(a,b,rtol=1e-2))                               
print(torch.allclose(a,b,rtol=1e-3))                              
print(torch.allclose(a,b,rtol=1e-4))                               
print(torch.allclose(a,b,atol=1e-1))                              
print(torch.allclose(a,b,atol=1e-2))                              
print(torch.allclose(a,b,atol=1e-3))                              
print(torch.allclose(a,b,atol=1e-4))
#Listing 2.40 – Extracting dimensions of minimum and maximum values in a given tensor
a = torch.rand(3,3)
print(a)
print(a.shape)               
print(torch.argmax(a, dim=0))                
print(torch.argmax(a, dim=1))                
print(torch.argmin(a, dim=0))                
print(torch.argmin(a, dim=1))
#Listing 2.41 – Extracting the indices of sorted values of a tensor
a = torch.rand(3,3)
print(a)
print(a.shape)          
print(torch.argsort(a, dim=0))
print(torch.argsort(a, dim=1))

In [ ]:
#Listing 2.42 – Cumulative sum along a dimension of the tensor
a = torch.rand(3,3)
print(a)
print(a.shape)                
b = torch.cumsum(a, dim=0)               
print(b)
print(b.shape)
c = torch.cumsum(a, dim=1)                                
print(c)
print(c.shape)
#Listing 2.43 – Cumulative product along a dimension of the tensor
a = torch.rand(3,3)
print(a)
print(a.shape)         
b = torch.cumprod(a, dim=0)                
print(b)                                
print(b.shape)                                
c = torch.cumprod(a, dim=1)                                
print(c)
print(c.shape)
#Listing 2.44 – Absolute value of a tensor
a = torch.tensor([[1,-1,1],[1,-1,1],[1,-1,1]])
print(a)
b = torch.abs(a)
print(b)
#Listing 2.45 – Clamping values within a tensor
a = torch.rand(3,3)
print(a)
b = torch.clamp(a, min=0.25, max=0.50)                
print(b)
#Listing 2.46 – Ceil and floor operations within a tensor
a = torch.rand(3,3) * 100
print(a)
b = torch.floor(a)                
print(b)
c = torch.ceil(a)                                
print(c)

### Element-wise Mathematical Operations

In [ ]:
#Listing 2.47 – Element wise multiplication
a = torch.rand(3,3)
print(a)
                
b = torch.FloatTensor([[0, 1, 0],[1,1,1],[0,1,0]])
print(b)                                

c = torch.mul(a,b)                                
print(c)

In [ ]:
#Listing 2.48 – Element wise division
a = torch.rand(3,3)

print(a)                
b = torch.FloatTensor([[1, 2, 1],[2,2,2],[1,2,1]])
                
print(b)                                

c = torch.div(a,b)
print(c)

## Trigonometric Operations in Tensors

In [ ]:
#Listing 2.49 – Basic Trigonometric operations for tensors
a = torch.linspace(-1.0, 1.0, steps=10)

print(a)

print(torch.sin(a))
                  
print(torch.cos(a))

print(torch.tan(a))
                                   
print(torch.asin(a))
                                            
print(torch.acos(a))
                                                    
print(torch.atan(a))


In [ ]:
#Listing 2.50 – Additional Trigonometric operations for tensors
a = torch.linspace(-1.0, 1.0, steps=10)

print(a)
         
print(torch.sigmoid(a))
                 
print(torch.tanh(a))
                          
print(torch.log1p(a))
                                   
print(torch.erf(a))
                                            
print(torch.erfinv(a))


## Comparison operations for tensors

In [ ]:
#Listing 2.51 – Comparison operations for tensors
a = torch.rand(3,3)

print(a)               

b = torch.rand(3,3)
                
print(b)                                

print(torch.ge(a,b))

print(torch.le(a,b))
                                                                
print(torch.eq(a,b))

print(torch.ne(a,b))


## Linear Algebraic Operations

In [ ]:
#Listing 2.52 – Matrix multiplication operations for tensors
a = torch.ones(2,3)
print("a -")
print(a)
print(a.shape)

print("b -")
b = torch.ones(3,2)
print(b)
print(b.shape)

print("\nMultiplication - ")
print(torch.matmul(a,b))

#The `addbmm` function (where bmm stands for batch matrix-matrix product) allows us to perform the computation `p * m + q * [a1 * b1 + a2 * b2 + ...]` where `p` and `q` are scalars and `m`, `a1`, `b1` , `a2` and `b2` are tensors. Note that the `addbmm` takes parameters `p` and `q` with default values equal to one and that tensors such as `a1` and `a2` are provided by stacking them along the first dimension. The example below illustrates the same.


In [ ]:
#Listing 2.53 – Batch matrix matrix addition of tensors
a = torch .ones(2, 2, 3)
print("a-")
print(a)                          
print(a.shape)

b = torch.ones(2, 3, 2)
print("b-")
print(b)
print(b.shape)

print("m-")
m = torch.ones(2,2)
                                                                      
print(m)                                                                              
print(m.shape)
                                                                              

print("BMM- 2 .  3")
print(torch.addbmm(2, m, 3, a, b))
print(torch.addbmm(m, a, b, beta=2, alpha=3,))

print("BMM- 1 .  1")
print(torch.addbmm(1, m, 1, a, b))


print("BMM-")
print(torch.addbmm(m, a, b))


In [ ]:
M = torch.randn(3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
result = torch.addbmm(M, batch1, batch2)
print(result)

In [72]:
#Listing 2.54 –Non Batch matrix matrix addition of tensors
a = torch.ones(2, 3)
print("a-") 
print(a)
print(a.shape)

b = torch.ones(3, 2)
print("b-")        
print(b)
print(b.shape)


m = torch.ones(2,2)
print("m-") 
                        
print(m)
print(m.shape)

print("ADDMM")
print(torch.addmm(m, a, b))

print("ADDMM - 2 . 3")
print(torch.addmm(2, m, 3, a, b))

print("ADDMM - 1 . 1")
print(torch.addmm(1, m, 1, a, b))


a-
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
b-
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.Size([3, 2])
m-
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
ADDMM
tensor([[4., 4.],
        [4., 4.]])
ADDMM - 2 . 3
tensor([[11., 11.],
        [11., 11.]])
ADDMM - 1 . 1
tensor([[4., 4.],
        [4., 4.]])


In [ ]:
#Listing 2.55 – matrix vector addition of tensors

a = torch.ones(2, 3)

print("a - ")        
print(a)
print(a.shape)


b = torch.ones(3)
print("b - ")        
print(b)
print(b.shape)

m = torch.ones(2)
print("m - ")        
print(m)
print(m.shape)
        
print("ADDMV- 2 . 2")        
torch.addmv(2,m,3,a,b)

print("ADDMV- 1 . 1")                
torch.addmv(1,m,1,a,b)

print("ADDMV-")   
torch.addmv(m,a,b)




In [ ]:
#Listing 2.56 – Outer product of vectors
a = torch.tensor([1.0, 2.0, 3.0])
print("a - ")        
print(a)
print(a.shape)


b = a

m = torch.ones(3,3)
print("m - ")        
print(m)
print(m.shape)

print("ADDR -")                    
print(torch.addr(m,a,b))
        
m = torch.zeros(3,3)

print("m - ")        
print(m)
                
print("ADDR -")    
print(torch.addr(m,a,b))

In [73]:
#Listing 2.57 – Illustration for baddbmm
a = torch.ones(2,2,3)
print("a - ")        
print(a)
print(a.shape)
                          
b = torch.ones(2,3,2)
print("b - ")        
print(b)
print(b.shape)                                                                      


m = torch.ones(2, 2, 2)
print("m - ")        
print(m)
print(m.shape)                                                                                                

print("BADDBMM - 1,m,1,a,b")
print(torch.baddbmm(1,m,1,a,b))

print("BADDBMM - 2,m,1,a,b")
print(torch.baddbmm(2,m,1,a,b))

print("BADDBMM - 1,m,3,a,b")
print(torch.baddbmm(1,m,2,a,b))


a - 
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
b - 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
torch.Size([2, 3, 2])
m - 
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])
BADDBMM - 1,m,1,a,b
tensor([[[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]]])
BADDBMM - 2,m,1,a,b
tensor([[[5., 5.],
         [5., 5.]],

        [[5., 5.],
         [5., 5.]]])
BADDBMM - 1,m,3,a,b
tensor([[[7., 7.],
         [7., 7.]],

        [[7., 7.],
         [7., 7.]]])


In [ ]:
#Listing 2.58 – Illustration for batch-wise matrix multiplication
a = torch.ones(2,2,3)
print("a - ")        
print(a)
print(a.shape)                                                                                                

b = torch.ones(2,3,2)
print("b - ")        
print(b)
print(b.shape)                                                                                                

print("BMM a.b")
print(torch.bmm(a,b))


In [ ]:
#Listing 2.59 – Dot product for tensors
a = torch.rand(3)
print("a-")
print(a)

b = torch.rand(3)
print("b-")
print(b)

print("Dot -- A.b")
print(torch.dot(a,b))


In [ ]:
#Listing 2.60 – Compute Eigen values
a = torch.rand(3,3)

print("a-",a)                

values, vectors = torch.eig(a, eigenvectors=True)
                
print("Values:",values)
                                
print("Vectors:",vectors)
   

print(values[0,0] * vectors[:,0].reshape(3,1))

print(torch.mm(a, vectors[:,0].reshape(3,1)))


In [ ]:
#Listing 2.61 – Cross product of two tensors
a = torch.rand(3)
b = torch.rand(3)

print("Cross Product ")
print(torch.cross(a,b))



In [ ]:
#Listing 2.62 – Compute the norm of a tensor

a = torch.ones(4)

print("Norm(a,1)-")
print(torch.norm(a,1))

print("Norm(a,2)-")
print(torch.norm(a,2))

print("Norm(a,3)-")
print(torch.norm(a,3))

print("Norm(a,4)-")
print(torch.norm(a,4))

print("Norm(a,5)-")
print(torch.norm(a,5))

print("Norm(a,Inf)-")
print(torch.norm(a,float('inf')))



In [ ]:
#Listing 2.63 – Normalize a tensor
a = torch.FloatTensor([[1,2,3,4]])
print("a-")
print(a)

print("renorm(a)")
print(torch.renorm(a, dim=0, p=2, maxnorm=1))

